import { FunctionsHttpError, type SupabaseClient } from "@supabase/supabase-js";

import type { Database } from "./database.types";

export type ExportStatus = Database["public"]["Enums"]["export_status"];
export type ExportType = Database["public"]["Enums"]["export_type"];

/** Private bucket `gedcom-export` writes to (migration 20260830231234). The
 * function stores `<jobId>.ged` at the bucket root and records
 * `export_job.storage_path = 'exports/<jobId>.ged'`. */
export const EXPORTS_BUCKET = "exports";

/** Lifetime of a download URL minted by {@link signExportDownload}. Minted on
 * click, so it only has to outlive the browser starting the download. */
export const EXPORT_DOWNLOAD_TTL_SECONDS = 3600;

/** How many past jobs the `/import` page lists. */
export const EXPORT_JOB_LIST_LIMIT = 20;

/** Same cap the function's own `fail()` applies to `error_text`. */
const ERROR_TEXT_MAX_CHARS = 500;

/** The `export_job` columns the `/import` UI reads. */
export interface ExportJob {
  readonly id: string;
  readonly type: ExportType;
  readonly status: ExportStatus;
  readonly storagePath: string | null;
  readonly sizeBytes: number | null;
  readonly errorText: string | null;
  /** ISO timestamp. */
  readonly createdAt: string;
  /** ISO timestamp, null until the function finishes. */
  readonly completedAt: string | null;
}

/** Everything {@link createExportJob} needs; the id is generated by the caller
 * so the same value names the row, the storage object, and the function call. */
export interface NewExportJob {
  readonly id: string;
  /** `account.id` of the moderator starting the export. */
  readonly startedBy: string;
}

const JOB_COLUMNS =
  "id, type, status, storage_path, size_bytes, error_text, created_at, completed_at";

type Db = SupabaseClient<Database>;
type ExportJobInsert = Database["public"]["Tables"]["export_job"]["Insert"];

/**
 * Insert a `manual_gedcom` job row. `status` defaults to `'pending'`; the
 * function moves it to `running` and then `completed` / `failed`. RLS
 * (`export_job_write`) requires an active moderator.
 */
export async function createExportJob(
  client: Db,
  job: NewExportJob,
): Promise<void> {
  const row: ExportJobInsert = {
    id: job.id,
    type: "manual_gedcom",
    started_by: job.startedBy,
  };
  const { error } = await client.from("export_job").insert(row);

  if (error !== null) {
    throw new Error(`createExportJob(${job.id}): ${error.message}`);
  }
}

/**
 * Invoke the `gedcom-export` edge function for a job. The browser client sends
 * the moderator's JWT, which the function accepts (SPEC §7). The call returns
 * only when the file is built — there is no cursor to resume from — so the
 * caller reads `export_job` afterwards rather than trusting the response body.
 *
 * Never throws for the call itself — the two ways it can go wrong mean
 * different things to the flow, so they come back as a discriminated result:
 * - `refused`: the function answered with a non-2xx. A job-level failure (an
 *   empty tree, a failing write) is a 422 with `error_text` already on the
 *   row. A refusal before the engine ran (401 / 403 / 400) leaves the row
 *   `pending`, and the shell's `{ error }` body is the only explanation.
 *   Either way the function is done with the row.
 * - `transport`: no answer (network drop, abort). The function may still be
 *   working, or may never have received the call.
 */
export async function invokeGedcomExport(
  client: Db,
  jobId: string,
): Promise<InvokeOutcome> {
  const { error } = await client.functions.invoke("gedcom-export", {
    body: { jobId },
  });

  if (error === null) {
    return { ok: true };
  }
  if (error instanceof FunctionsHttpError) {
    return {
      ok: false,
      kind: "refused",
      message: await functionErrorDetail(error),
    };
  }
  return { ok: false, kind: "transport", message: messageOf(error) };
}

export type InvokeOutcome =
  | { readonly ok: true }
  | {
      readonly ok: false;
      readonly kind: "refused" | "transport";
      readonly message: string;
    };

/**
 * Record a failure the engine never got to write (the function refused before
 * it ran, or never received the call), so the row does not sit in the
 * past-jobs list as "Queued" forever. Guarded on `status = 'pending'`: a
 * function that did start owns the row from then on and this becomes a no-op.
 * `completed_at` stays null, as it does when the function's own `fail()`
 * writes a failure. RLS (`export_job_write`) lets a moderator update the row.
 */
export async function markExportJobFailed(
  client: Db,
  jobId: string,
  message: string,
): Promise<void> {
  const { error } = await client
    .from("export_job")
    .update({
      status: "failed",
      error_text: message.slice(0, ERROR_TEXT_MAX_CHARS),
    })
    .eq("id", jobId)
    .eq("status", "pending");

  if (error !== null) {
    throw new Error(`markExportJobFailed(${jobId}): ${error.message}`);
  }
}

/** Read the current state of a job. */
export async function getExportJob(
  client: Db,
  jobId: string,
): Promise<ExportJob> {
  const { data, error } = await client
    .from("export_job")
    .select(JOB_COLUMNS)
    .eq("id", jobId)
    .single();

  if (error !== null) {
    throw new Error(`getExportJob(${jobId}): ${error.message}`);
  }
  return parseExportJob(data);
}

/** The most recent jobs, newest first, capped at {@link EXPORT_JOB_LIST_LIMIT}. */
export async function listExportJobs(
  client: Db,
): Promise<readonly ExportJob[]> {
  const { data, error } = await client
    .from("export_job")
    .select(JOB_COLUMNS)
    .order("created_at", { ascending: false })
    .limit(EXPORT_JOB_LIST_LIMIT);

  if (error !== null) {
    throw new Error(`listExportJobs: ${error.message}`);
  }
  return data.map(parseExportJob);
}

/**
 * Mint a fresh download URL for a completed job's file. Minted on demand rather
 * than stored: the function's own URL expires after an hour, but the object
 * stays in the bucket, and a moderator can sign it again at any time
 * (`exports_moderator_all` grants `select` on the object row).
 *
 * `download` names the saved file — without it the browser would save
 * `<uuid>.ged`.
 */
export async function signExportDownload(
  client: Db,
  job: ExportJob,
): Promise<string> {
  const key = exportObjectKey(job);
  if (key === null) {
    throw new Error(`signExportDownload(${job.id}): no file to download`);
  }
  const { data, error } = await client.storage
    .from(EXPORTS_BUCKET)
    .createSignedUrl(key, EXPORT_DOWNLOAD_TTL_SECONDS, {
      download: exportDownloadFilename(job),
    });

  if (error !== null) {
    throw new Error(`signExportDownload(${job.id}): ${error.message}`);
  }
  return data.signedUrl;
}

/** True when the job finished and left a file behind to sign. */
export function isDownloadable(job: ExportJob): boolean {
  return job.status === "completed" && exportObjectKey(job) !== null;
}

/**
 * The object key inside {@link EXPORTS_BUCKET}: `storage_path` minus the bucket
 * prefix. Null when the row has no path yet, or one outside the bucket. Exported
 * for tests.
 */
export function exportObjectKey(job: ExportJob): string | null {
  const prefix = `${EXPORTS_BUCKET}/`;
  if (job.storagePath === null || !job.storagePath.startsWith(prefix)) {
    return null;
  }
  const key = job.storagePath.slice(prefix.length);
  return key === "" ? null : key;
}

/** `rootward-2026-09-12.ged`, dated from `completed_at` (falls back to
 * `created_at`). Exported for tests. */
export function exportDownloadFilename(job: ExportJob): string {
  const stamp = (job.completedAt ?? job.createdAt).slice(
    0,
    "YYYY-MM-DD".length,
  );
  return `rootward-${stamp}.ged`;
}

// --- boundary parsing ----------------------------------------------------

/** The subset of the table row {@link JOB_COLUMNS} selects. Tied to the
 * generated schema so a column rename breaks the build here. */
type ExportJobRow = Pick<
  Database["public"]["Tables"]["export_job"]["Row"],
  | "id"
  | "type"
  | "status"
  | "storage_path"
  | "size_bytes"
  | "error_text"
  | "created_at"
  | "completed_at"
>;

function parseExportJob(row: ExportJobRow): ExportJob {
  return {
    id: row.id,
    type: row.type,
    status: row.status,
    storagePath: row.storage_path,
    sizeBytes: row.size_bytes,
    errorText: row.error_text,
    createdAt: row.created_at,
    completedAt: row.completed_at,
  };
}

/**
 * The function shell answers every refusal with `{ error: "<why>" }`.
 * `FunctionsHttpError.message` is the generic "non-2xx status code", so read
 * the body when there is one. `context` is typed `any` upstream; narrow it to a
 * `Response` before touching it.
 */
async function functionErrorDetail(error: FunctionsHttpError): Promise<string> {
  const context: unknown = error.context;
  if (!(context instanceof Response)) {
    return error.message;
  }
  try {
    const body: unknown = await context.json();
    if (
      typeof body === "object" &&
      body !== null &&
      "error" in body &&
      typeof body.error === "string"
    ) {
      return body.error;
    }
  } catch {
    // Not JSON — fall through to the status line.
  }
  return `${error.message} (HTTP ${context.status})`;
}

/** `functions.invoke` types its `error` as `any`; narrow before reading it. */
function messageOf(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
