import type { SupabaseClient } from "@supabase/supabase-js";
import {
  encodeMediaStorageKey,
  GEDCOM_OBJECT_NAME,
  MEDIA_META_OBJECT_NAME,
  MEDIA_SUBPREFIX,
  type MediaMetaJson,
} from "@rootward/gedcom";
import { EXTENSION_FOR_MIME } from "@rootward/media";
import type { ReadyMediaFile } from "@rootward/media";

import type { Database, Json } from "./database.types";

export type ImportStatus = Database["public"]["Enums"]["import_status"];
export type ImportMode = Database["public"]["Enums"]["import_mode"];

/** Private bucket the `/import` upload lands in (migration 20260830235147). */
export const IMPORTS_BUCKET = "imports";

/** Storage *prefix* for a job's uploaded files: `imports/<jobId>` (issue
 * #104). `uploadImportFiles` writes the GEDCOM text at
 * `<prefix>/gedcom.ged` and, for a GedZip, each media file under
 * `<prefix>/media/` -- see `@rootward/gedcom`'s `media-storage-keys` module,
 * which both this and the `gedcom-import` edge function's gateway import so
 * the object-name/key contract can't drift between the two sides. */
export function importStoragePrefix(jobId: string): string {
  return `${IMPORTS_BUCKET}/${jobId}`;
}

/**
 * Running totals the `gedcom-import` engine writes to `import_job.stats`
 * (SPEC §7). `warnings` collects dropped references and junk place values that
 * did not fail the import.
 */
export interface ImportStats {
  readonly added: number;
  readonly updated: number;
  readonly skipped: number;
  readonly removed: number;
  readonly warnings: readonly string[];
}

/** The `import_job` columns the `/import` UI reads. */
export interface ImportJob {
  readonly id: string;
  readonly status: ImportStatus;
  readonly mode: ImportMode;
  readonly filename: string | null;
  readonly processedRecords: number;
  readonly totalRecords: number | null;
  readonly stats: ImportStats;
  readonly errorText: string | null;
}

/** Everything {@link createImportJob} needs; the id is generated by the caller
 * so the same value names the row, the storage object, and the function call. */
export interface NewImportJob {
  readonly id: string;
  readonly filename: string;
  /** `account.id` of the moderator starting the import — becomes
   * `created_by` / `updated_by` on every row the engine writes (SPEC §7). */
  readonly startedBy: string;
  readonly mode?: ImportMode;
}

const JOB_COLUMNS =
  "id, status, mode, filename, processed_records, total_records, stats, error_text";

type Db = SupabaseClient<Database>;
type ImportJobInsert = Database["public"]["Tables"]["import_job"]["Insert"];

/**
 * Insert the job row, already pointing at the storage key its file will land
 * at. `status` defaults to `'uploaded'`. RLS (`import_job_insert`) requires an
 * active moderator.
 */
export async function createImportJob(
  client: Db,
  job: NewImportJob,
): Promise<void> {
  const row: ImportJobInsert = {
    id: job.id,
    mode: job.mode ?? "initial",
    filename: job.filename,
    started_by: job.startedBy,
    storage_path: importStoragePrefix(job.id),
  };
  const { error } = await client.from("import_job").insert(row);

  if (error !== null) {
    throw new Error(`createImportJob(${job.id}): ${error.message}`);
  }
}

/**
 * Upload the job's GEDCOM text and its already-processed media (issue #104
 * pts. 1 and 2: a GedZip is unzipped client-side, and each photo is decoded/
 * resized/EXIF-stripped client-side too -- `prepareImportUpload` +
 * `processImportMedia` -- because the edge function's fixed memory and
 * CPU-time budget cannot reliably fit either for a real archive). The
 * GEDCOM text lands at `<jobId>/gedcom.ged`; each media item gets its own
 * `<jobId>/media/<key>/` folder holding a small `meta.json` plus whichever
 * of `original.<ext>` / `thumb.webp` / `display.webp` its outcome produced.
 * Sequential, not `Promise.all` -- a real GedZip uploads well over a hundred
 * small objects, and unbounded concurrency has no precedent elsewhere in
 * this codebase to justify the added complexity for what is, locally, a
 * fast loop either way. `upsert` throughout so a retry of the same job
 * overwrites rather than 409s.
 */
export async function uploadImportFiles(
  client: Db,
  jobId: string,
  gedcomText: string,
  media: ReadonlyMap<string, ReadyMediaFile>,
): Promise<void> {
  await uploadObject(
    client,
    `${jobId}/${GEDCOM_OBJECT_NAME}`,
    new TextEncoder().encode(gedcomText),
    "text/plain",
  );

  let index = 0;
  for (const [archivePath, ready] of media) {
    const itemPrefix = `${jobId}/${MEDIA_SUBPREFIX}/${encodeMediaStorageKey(index, archivePath)}`;
    index += 1;

    if (ready.status === "rejected") {
      await uploadJson(client, `${itemPrefix}/${MEDIA_META_OBJECT_NAME}`, {
        status: "rejected",
        rejectReason: ready.rejectReason,
      });
      continue;
    }

    const extension = EXTENSION_FOR_MIME[ready.mimeType] ?? "bin";
    await uploadObject(
      client,
      `${itemPrefix}/original.${extension}`,
      ready.originalBytes,
      ready.mimeType,
    );
    if (ready.derivatives !== null) {
      await uploadObject(
        client,
        `${itemPrefix}/thumb.webp`,
        ready.derivatives.thumb,
        "image/webp",
      );
      await uploadObject(
        client,
        `${itemPrefix}/display.webp`,
        ready.derivatives.display,
        "image/webp",
      );
    }
    await uploadJson(client, `${itemPrefix}/${MEDIA_META_OBJECT_NAME}`, {
      status: "processed",
      mimeType: ready.mimeType,
      hasDerivatives: ready.derivatives !== null,
      hasGps: ready.exif.hasGps,
      gpsStripped: ready.exif.gpsStripped,
      warnings: ready.warnings,
    });
  }
}

async function uploadObject(
  client: Db,
  key: string,
  bytes: Uint8Array,
  contentType: string,
): Promise<void> {
  const { error } = await client.storage
    .from(IMPORTS_BUCKET)
    .upload(key, bytes, { upsert: true, contentType });
  if (error !== null) {
    throw new Error(`uploadImportFiles: ${key}: ${error.message}`);
  }
}

function uploadJson(
  client: Db,
  key: string,
  value: MediaMetaJson,
): Promise<void> {
  return uploadObject(
    client,
    key,
    new TextEncoder().encode(JSON.stringify(value)),
    "application/json",
  );
}

/**
 * Invoke the `gedcom-import` edge function for a job. The browser client sends
 * the moderator's JWT, which the function accepts (SPEC §7). Safe to call again
 * while a job is mid-flight — the engine is idempotent and resumes from
 * `import_job.cursor`, which is how a client re-poll recovers a timed-out run.
 */
export async function invokeGedcomImport(
  client: Db,
  jobId: string,
): Promise<void> {
  const { error } = await client.functions.invoke("gedcom-import", {
    body: { jobId },
  });

  if (error !== null) {
    throw new Error(`invokeGedcomImport(${jobId}): ${error.message}`);
  }
}

/** Read the current state of a job. */
export async function getImportJob(
  client: Db,
  jobId: string,
): Promise<ImportJob> {
  const { data, error } = await client
    .from("import_job")
    .select(JOB_COLUMNS)
    .eq("id", jobId)
    .single();

  if (error !== null) {
    throw new Error(`getImportJob(${jobId}): ${error.message}`);
  }
  return parseImportJob(data);
}

// --- boundary parsing ----------------------------------------------------

/** The subset of the table row {@link JOB_COLUMNS} selects. Tied to the
 * generated schema so a column rename breaks the build here. */
type ImportJobRow = Pick<
  Database["public"]["Tables"]["import_job"]["Row"],
  | "id"
  | "status"
  | "mode"
  | "filename"
  | "processed_records"
  | "total_records"
  | "stats"
  | "error_text"
>;

function parseImportJob(row: ImportJobRow): ImportJob {
  return {
    id: row.id,
    status: row.status,
    mode: row.mode,
    filename: row.filename,
    processedRecords: row.processed_records,
    totalRecords: row.total_records,
    stats: parseImportStats(row.stats),
    errorText: row.error_text,
  };
}

/** `stats` is `jsonb` — typed only as `Json` — so coerce it once here. The
 * engine is the only writer, so an unexpected shape means a bug upstream:
 * fall back to zeros rather than crash the result screen, but keep it visible
 * in `warnings` if the engine put one there. */
export function parseImportStats(raw: Json): ImportStats {
  const source: Record<string, unknown> =
    typeof raw === "object" && raw !== null && !Array.isArray(raw) ? raw : {};

  return {
    added: countOf(source.added),
    updated: countOf(source.updated),
    skipped: countOf(source.skipped),
    removed: countOf(source.removed),
    warnings: Array.isArray(source.warnings)
      ? source.warnings.filter((w): w is string => typeof w === "string")
      : [],
  };
}

function countOf(value: unknown): number {
  return typeof value === "number" && Number.isInteger(value) && value >= 0
    ? value
    : 0;
}
